### PR TITLE
feat: filter by operation ids

### PR DESCRIPTION
**Pull request by johanneswuerbach**
When generating server mocks or clients we often only need specific operations to be included. Right now we workaround this issue by having unique operation tags, but this has various side-effects.

Add the capability to include or exclude specific operations by their operation id inline with the existing support to filter by tags.

### CODE REVIEW

**Comment by johanneswuerbach** [comment]
I would also appreciate a look here @deepmap-marcinr and sorry about the spam :-(

**Comment by johanneswuerbach** [comment]
@deepmap-marcinr is this something, which would be acceptable for this repository? Happy to further elaborate on our use-case.

**Comment by jamietanna** [comment]
Hey @johanneswuerbach thanks for raising! Would you mind adding an example of the usage under `internal/test`, just to show what it would look like + ensure we've got a test to catch regressions in the future

Once done, I'd say we can merge :grin:

**Comment by johanneswuerbach** [comment]
Thanks for the review @jamietanna , integration tests added 👍

**Comment by johanneswuerbach** [comment]
@jamietanna anything else I can support here? Thank you 🙇

**Comment by johanneswuerbach** [comment]
@jamietanna I know you are busy, but I wondered if there is any chance to land this :-)

**Review by jamietanna — APPROVED** [review]
Thank you for this!

**Pull request merged**
