### PR TITLE
fix(deps): update kin-openapi to v0.104.0

### PR DESCRIPTION
**Pull request by mgabeler-lee-6rs**
Adapt to breaking changes from v0.103.0: https://github.com/getkin/kin-openapi#v01130

Supersedes dependabot attempt in #951

### CODE REVIEW

**Comment by derbylock** [comment]
What are the reasons it is not yet merged?

**Comment by mgabeler-lee-6rs** [comment]
@derbylock It's waiting for attention from the maintainers. Who exactly that is is not clear, since the `deepmap` organization doesn't make its members public, and the repo doesn't have a contributing guide.

@deepmap-marcinr Apologies if you're the wrong person, but you've merged a lot of the most recent PRs, so hoping you can get eyes on this.

**Comment by deepmap-marcinr** [comment]
Sorry, I'm just one guy and super busy. I'm the "organization" :)

**Comment by mgabeler-lee-6rs** [comment]
@deepmap-marcinr no worries, and thank you :grin:

**Comment by zekth** [comment]
Could this be released? 🙏

**Comment by mweibel** [comment]
sorry to add to the noise but I'd be glad for a release, too :slightly_smiling_face:

**Comment by deepmap-marcinr** [comment]
I'm planning on one in not too long, let me deal with more PR's. For now, you can always pin your module to a specific SHA.

**Pull request merged**
