### PR TITLE
Query Params struct tag should be "form" instead of "json"

### PR DESCRIPTION
**Pull request by djeer**
Fix for issue https://github.com/deepmap/oapi-codegen/issues/500
Query params will be generated with tag "form" instead of tag "json"

### CODE REVIEW

**Comment by djeer** [comment]
image

**Comment by djeer** [comment]
Checked on the code from master branch, auto-generated server reads parameters using "form" argument, so it's type hints that are wrong  
image

**Comment by deepmap-marcinr** [comment]
Sorry to respond to this so late. I'm happy to merge this - but can we have both annotations, 'json' and 'form'? There's lots of existing JSON serialization which will break.

**Comment by djeer** [comment]
Sorry for late response as well 😄 Looks like this PR can be closed since the fix was applied https://github.com/deepmap/oapi-codegen/commit/6a3482493b5731b60c267147522ec3aaa09fc3a3

**Pull request closed without merging**
