### PR TITLE
Add support for strict server with Gorilla

### PR DESCRIPTION
**Pull request by DouglasDwyer**
This PR adds an extra template which supports strict server generation with Gorilla mux. The template is very similar to the Chi server template.

### CODE REVIEW

**Comment by Warboss-rus** [comment]
Why not just use chi template and generate it for gorilla? There is no router-specific code in strict templates

**Comment by DouglasDwyer** [comment]
Agreed - there is no router-specific code in the Chi server template, so it could work in lieu of something Gorilla-specific. Currently, calling oapi-codegen with the `gorilla` and `strict` options just doesn't generate the strict server implementation at all. Should I replace the reference to the Gorilla template in `operations.go` with a reference to Chi server? If we choose to do this, might it make more sense to rename the strict Chi server to something more neutral (like StrictHTTPServer)?

**Comment by Warboss-rus** [comment]
Yeah, you can rename the template to strict-http and generate it for both chi and gorilla

**Comment by DouglasDwyer** [comment]
Sounds good. I've gone ahead and made the requested changes.

**Review by Warboss-rus — APPROVED** [review]
LGTM

**Comment by jamietanna** [comment]
This would close #714 if merged - thanks for raising, quick glance on mobile looks good, but will have a proper review later 🤞🏽

**Comment by deepmap-marcinr** [comment]
It looks like the generated files need to be regenerated for precommit to pass.

**Pull request merged**
