### PR TITLE
Fix client request url construction when colon in path

### PR DESCRIPTION
**Pull request by bvwells**
Fix client request url construction when colon in path. Fixes issue #312.

### CODE REVIEW

**Comment by bvwells** [comment]
Need to test...

**Comment by bvwells** [comment]
@deepmap-marcinr thanks for the review and merge!

**Comment by rkojedzinszky** [comment]
Unfortunately, this breaks cases when a request parameter contains '/'. Earlier, this got escaped well, now an argument of 'main/i' gets escaped as: `main%252Fi`.

**Comment by bvwells** [comment]
@rkojedzinszky can you provide an example spec and I'll take a look.

**Comment by rkojedzinszky** [comment]
@bvwells I used latest, v1.5.2. The spec is a freenas 11.3 openapi, attached.
[freenas-11.3-openapi.json.gz](https://github.com/deepmap/oapi-codegen/files/6166710/freenas-11.3-openapi.json.gz)

For example, at path `/pool/dataset/id/{id}` the id parameter may be a zfs volume, containing `/`.

**Comment by deepmap-marcinr** [comment]
I've got a fix for this which does what @bvwells  did in the client, but he missed the corresponding server side change to unescape arguments, so I fixed that side as well.

Your code used to work @rkojedzinszky because we got lucky to be consistently wrong :)

**Comment by bvwells** [comment]
Sorry for missing this on the server side. Glad we got to the bottom of it as I couldn't work out what was wrong client side.

**Pull request merged**
