### PR TITLE
Reverse the order of the middleware when they applied in gorilla/mux implementation

### PR DESCRIPTION
**Pull request by mpls104**
resolve https://github.com/deepmap/oapi-codegen/issues/841

### CODE REVIEW

**Review by stevenh — APPROVED** [review]
LGTM

**Comment by jamietanna** [comment]
Thanks for this - looks like this was because I copy-pasta'd Chi's server, and was resolved there in #787

**Review by jamietanna — CHANGES_REQUESTED** [review]
Looks good - only requested change is that similar to [the Chi PR](https://github.com/deepmap/oapi-codegen/pull/787), we add a compatibility option to allow folks to opt-in to these?

**Comment by mpls104** [comment]
@jamietanna 
Addressed in 4b9090ff9ee59594b1555dabb7c072925b7389c4

**Review by jamietanna — APPROVED** [review]
Looks good, thanks for the changes :raised_hands: 

Only thought I have is whether we should rename the flag:

```suggestion
-apply-gorilla-mux-middleware-first-to-last
+apply-gorilla-middleware-first-to-last
```

Given the configuration to generate gorilla/mux servers is `gorilla-server`?

**Comment by mpls104** [comment]
Understood. Since `GenerateOptions` has already named as `gorilla-server`, let's omit the word `mux`. I'll push commit to fix them.

**Pull request merged**
