### PR TITLE
implement new field: x-go-type-import

### PR DESCRIPTION
**Pull request by VladimirStepanov**
Close https://github.com/deepmap/oapi-codegen/issues/498

### CODE REVIEW

**Comment by Viltonhoy** [comment]
Tried to use your x-go-type with an imported type but as a result it produces a pointer to this type. Do you have nullable in your code?

**Comment by VladimirStepanov** [comment]
@Viltonhoy oapi-codegen generates pointer for type when field is not required
```yaml
schemas:
      Pet:
        properties:
          age:
            x-go-type: uuid.UUID
            x-go-type-import:
              path: github.com/google/uuid
```

Result:
```go
type Pet struct {
	Age uuid.UUID `json:"age"`
}
```

**Comment by VladimirStepanov** [comment]
@deepmap-marcinr Hello, could you check this changes plz, if you have free time?:)

**Comment by othalla** [comment]
Wht not testing the `codegen.go` file ?

**Comment by VladimirStepanov** [comment]
@othalla thanks for your comment, I fixed it

**Review by m68kadse — APPROVED** [review]

**Review by stsem — APPROVED** [review]

**Comment by stsem** [comment]
I'm really looking forward to this PR in the master

**Pull request merged**
