### PR TITLE
return 404 when no matching route is found

### LINKED ISSUE #1066: [middleware] Request validator should return 404 not 400 if route is unable to be found
This line should return `return http.StatusNotFound, err // We failed to find a matching route for the request.`

https://github.com/deepmap/oapi-codegen/blob/14548c7e7bbee8d8fbd7e706f9b6f9e3381b44fb/pkg/chi-middleware/oapi_validate.go#L75-L81

Thoughts?

### PR DESCRIPTION
**Pull request by sonu27**
Closes #1066

### CODE REVIEW

**Comment by jxsl13** [comment]
Should be 405. 404 is resource not found contrary to method not allowed/ not registered.

**Comment by sonu27** [comment]
Currently, it's returning 400 which is not correct.
If you hit most servers on the web where a route does not exist e.g. https://google.com/asdfadsfasdfasdf you will get 404.
405 is if the route exists but method is different.

**Comment by jxsl13** [comment]
fair point

**Comment by sonu27** [comment]
Just updated other middlewares too

**Comment by sonu27** [comment]
@deepmap-marcinr What do you think?

**Pull request merged**
