### PR TITLE
ci: enable more linters and fix issues

### PR DESCRIPTION
**Pull request by stevenh**
Enable more linters for `golangci-lint` and fix the issues that the additional linters highlight.

This addresses:
* Missing error checks.
* Duplicate code.
* Direct error comparison instead of `errors.As` or `errors.Is`.
* Missing error wrapping.
* Test helpers.
* Document comments.
* Missing http `Request.Body.Close()`
* Switches instead of complex ifs.
* Use `strings.ReplaceAll` instead of `strings.Replace` with -1.
* Unnecessary blank lines.
* Duplicate literal strings.
* Unneeded casts.
* Removed inits.
* Preallocate slices.
* Unused parameters and vars.
* Invalid error return when using time fallback case.

Also:
* Merge ci steps into one so it runs quicker.
* Add go 1.19 (latest) to validation.

### CODE REVIEW

**Review by 53jk1 — APPROVED** [review]

**Comment by stevenh** [comment]
@53jk1 do you want me to rebase to resolve conflicts?

**Comment by 53jk1** [comment]
@stevenh I think rebase would be good

**Comment by stevenh** [comment]
@53jk1 done

**Comment by jamietanna** [comment]
Thanks and sorry we didn't get around to accepting this. We've added some of the changes. If there are any linter rules that you think are worthwhile, please raise an issue and we can work out how best to decide when we want to add them (https://github.com/deepmap/oapi-codegen/issues/1587)

**Pull request closed without merging**
