### PR TITLE
Update jsonmerge.go

### PR DESCRIPTION
**Pull request by mrkouchaki**
uable to find /v2

### CODE REVIEW

**Comment by jamietanna** [comment]
Hey, not sure why this change is needed - I've got at least one project that's using the jsonmerge changes successfully :thinking:

**Comment by jxsl13** [comment]
there is a v2.0.0 tag but not a /v2 path. Don't know the implications of those for the versioning and import paths.

**Comment by jamietanna** [comment]
Good spot - this may be because the author has pinned the module version path inside go.mod - https://github.com/apapsch/go-jsonmerge/commit/90b01458c2af82553f17c56a431386c57a8a569f

**Comment by jamietanna** [comment]
@mrkouchaki any thoughts on the above? I'll probably move to close this as I don't think it's needed

**Pull request closed without merging**
