### PR TITLE
Fix broken build due to kin backwards-incompatible change

### PR DESCRIPTION
**Pull request by nevivurn**
There was a backwards-incompatible change in `github.com/getkin/kin-openapi` 0.51.0: getkin/kin-openapi#326

This PR fixes the build & hopefully maintains the old behavior. Unfortunately, this means panicking on error, since that's what kin-openapi used to do: https://github.com/getkin/kin-openapi/blob/v0.50.0/openapi3filter/router.go#L87-L94

### CODE REVIEW

**Comment by deepmap-marcinr** [comment]
I had to roll this back.

Pulling in that routers/legacy package forces kin-openapi 0.52.0, which uses the //go:embed directive, which breaks on go 1.14, which is our minimum supported version.

**Comment by nevivurn** [comment]
Ah, I thought it was fine since oapi-codegen was using `kin-openapi v0.50.0` when I wrote this. Fair enough.

I'm guessing that issues like these are going to be common as long as kin-openapi is sub-v1 and continues having breaking changes, which is unfortunate, but I guess that's what we get for depending on something sub-v1.

For now, I'll work around this by depending on my own fork. Thanks for the good work!

**Comment by fenollp** [comment]
Hi, I maintain kin-openapi. As you may have noted the dependency on go:embed is only in a test. Let me see if I can have this test run iff go>1.14.

**Comment by deepmap-marcinr** [comment]
Oh cool!

@fenollp  - Thank you so much for your work on kin-openapi. I can't imagine writing API's without it.

**Pull request merged**
