### PR TITLE
Fiber support

### PR DESCRIPTION
**Pull request by JamsMendez**
Based on the need to use Echo as a template and manually make changes to Fiber, I tried to implement Fiber support. I would really appreciate any feedback, to improve my skill 😸. Thank

### CODE REVIEW

**Comment by leonklingele** [comment]
@JamsMendez have you seen https://github.com/deepmap/oapi-codegen/pull/813?

**Comment by JamsMendez** [comment]
Forgot to check if there is a pull request 😅 .
"Well we tried 🦖 "

**Comment by leonklingele** [comment]
Oh no! 🙈 Guess that happens 😄

I‘m currently helping to get the other PR merged. Do you see any obvious difference between your work and the other one?
Let‘s make this awesome together!

**Comment by leonklingele** [comment]
@JamsMendez https://github.com/deepmap/oapi-codegen/pull/813 is being merged soon. Want to take a look at it before that happens? :)

**Comment by JamsMendez** [comment]
@leonklingele, amazing and inspiring, thanks for considering me, I'll try to keep an eye out for a good contribution to the project. 😁

**Comment by jamietanna** [comment]
Closing as we merged #813 👏

**Pull request closed without merging**
