### PR TITLE
Types can be placed separately from the server side logic

### PR DESCRIPTION
**Pull request by sparshev**
Additional option to specify which module contains the generated types

### CODE REVIEW

**Comment by sparshev** [comment]
Hi @deepmap-marcinr, could you please suggest who can check the PR? If it's good - I can work on the tests and other required improvements to make sure it will fit perfectly.

**Comment by sparshev** [comment]
Hi @deepmap-marcinr could you please check this? Not sure if it's still actual though...

**Comment by tuxofil** [comment]
Rebased and adapted this patch in #558 . I think we can close it now.

**Comment by sparshev** [comment]
Thank you @tuxofil , I've got no review, so I switched to in-place patching and almost forgot about this change - for sure if yours will be merged I will close this one.

**Comment by sparshev** [comment]
Ok, now types could be separated the next way:
* For types package:
   ```yaml
   ---
   package: types
   output: types/types.gen.go
   generate:
     models: true
   ```
* For the server package:
   ```yaml
   ---
   package: api
   output: api/server_v1.gen.go
   generate:
     echo-server: true
   additional-imports:
     - alias: .  # means will be used without namespace prefix
       package: github.com/exampleorg/exampleproj/pkg/types  # full path to the types package
   ```

So the types will be available to use in server generated code.

**Pull request closed without merging**
