### PR TITLE
updated the version of echo & go

### PR DESCRIPTION
**Pull request by Taillook**
Updated echo v4.2.1 to v4.5.0
and go1.15

because problem by github.com/dgrijalva/jwt-go.
Includes security upgrades.

> So for JWT middleware users Go 1.15+ is required

ref: https://github.com/labstack/echo/releases/tag/v4.5.0

### CODE REVIEW

**Comment by Taillook** [comment]
@deepmap-marcinr 
Hi.
If possible, please check as soon.

**Comment by Taillook** [comment]
resolved conflict.

**Comment by Taillook** [comment]
@deepmap-marcinr 
fixed conflict.

**Comment by deepmap-marcinr** [comment]
I've started working on a V2 of this library, which will make compatibility easier, and that one's already on 1.16. If I merge this, we break compatibility with Go 1.14, which would mean increasing the semver major version. I guess we could push a release with a new minor version.

**Comment by Taillook** [comment]
@deepmap-marcinr 
recreated pull request on #430 for v2-dev.

**Pull request closed without merging**
